// build.mjs — generate machine-readable artifacts into generated/.
// DO NOT edit generated/ by hand. Run after validate.
// Output: surface-registry.yaml, navigation-graph.yaml, action-registry.csv, coverage-report.md

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import yaml from "js-yaml";
import { extractAll, SPEC_ROOT } from "./extract.mjs";

const OUT = join(SPEC_ROOT, "generated");
mkdirSync(OUT, { recursive: true });

const files = extractAll().filter((f) => f.contract);
const HEADER = "# GENERATED by ui-spec-tools/build.mjs — DO NOT EDIT BY HAND. Source = surface *.md\n";

// ---- surface-registry.yaml ----
const registry = { surfaces: {} };
for (const f of files) {
  const m = f.meta || {};
  if (!m.id) continue;
  registry.surfaces[m.id] = {
    type:      m.type,
    name:      m.name,
    platforms: m.platforms || [],
    hosts:     m.hosts     || [],
    status:    m.status    || "active",
    file:      f.file,
    rules:     m.rules     || [],
    regions:   m.regions   || [],
  };
}
writeFileSync(join(OUT, "surface-registry.yaml"), HEADER + yaml.dump(registry, { lineWidth: 120 }));

// ---- navigation-graph.yaml + action-registry.csv ----
const edges = [];
for (const f of files) {
  const m = f.meta || {};
  const c = f.contract;

  const pushEdge = (it, kind) => {
    // Strip internal _autoId marker from output
    const { _autoId, ...clean } = it;
    edges.push({
      id:          clean.id,
      from:        m.id,
      element:     clean.element,
      trigger:     clean.trigger,
      listens_to:  clean.listens_to,
      guard:       clean.guard,
      action:      clean.action ?? (kind === "emit" ? "emit_event" : undefined),
      target:      clean.target,
      event:       clean.event,
      payload:     clean.payload,
      effects:     clean.effects,
      region:      clean.region,
    });
  };

  for (const it of c.interactions || []) pushEdge(it, "interaction");
  for (const em of c.emits        || []) pushEdge(em, "emit");
}

// Strip undefined keys for clean YAML output
const cleanEdges = edges.map((e) =>
  Object.fromEntries(Object.entries(e).filter(([, v]) => v !== undefined))
);

writeFileSync(
  join(OUT, "navigation-graph.yaml"),
  HEADER + yaml.dump({ surfaces: Object.keys(registry.surfaces), edges: cleanEdges }, { lineWidth: 120 })
);

// action-registry.csv — flat table for spreadsheet/tooling consumption
const csvRows = [["id", "from", "trigger", "action", "target", "guard", "region"]];
for (const e of cleanEdges) {
  csvRows.push([
    e.id        ?? "",
    e.from      ?? "",
    e.trigger   ?? e.listens_to ?? "",
    e.action    ?? "",
    e.target    ?? "",
    (e.guard    ?? "").replaceAll(",", ";"),
    e.region    ?? "",
  ]);
}
writeFileSync(join(OUT, "action-registry.csv"), csvRows.map((r) => r.join(",")).join("\n") + "\n");

// ---- coverage-report.md ----
const flows = files.filter((f) => f.meta?.type === "flow" && f.contract?.flow);
const actionIds = new Set(cleanEdges.map((e) => e.id));

let cov = `<!-- GENERATED by ui-spec-tools/build.mjs — DO NOT EDIT BY HAND. Source = surface *.md -->\n\n`;
cov += `# Coverage Report (generated)\n\n`;
cov += `Surfaces: ${Object.keys(registry.surfaces).length} · Actions: ${cleanEdges.length} · Flows: ${flows.length}\n\n`;
cov += `## Flow → Actions\n\n| Flow | Goal | Steps | Missing action refs |\n|---|---|---|---|\n`;

for (const f of flows) {
  const fl = f.contract.flow;
  const steps   = (fl.steps    || []).concat((fl.branches || []).map((b) => b.action));
  const missing = steps.filter((s) => !actionIds.has(s));
  cov += `| ${f.meta.id} | ${fl.goal ?? ""} | ${(fl.steps || []).join(" → ")} | ${missing.length ? missing.join(", ") : "—"} |\n`;
}

writeFileSync(join(OUT, "coverage-report.md"), cov);

console.log(`✓ built generated/: surface-registry.yaml, navigation-graph.yaml, action-registry.csv, coverage-report.md`);
console.log(`  surfaces=${Object.keys(registry.surfaces).length} actions=${cleanEdges.length} flows=${flows.length}`);
