// decision-index.mjs — generates docs/decisions/index.md, a projection of
// state.decisions' platform/repo-wide decisions (those carrying a `scope`
// field, tsk-1lv-2 / CONTEXT.md D4). Mirrors two existing patterns rather
// than inventing a new one:
//   - docs/enduser-docs-index.json's own generate+drift shape
//     (enduser-index-generate.mjs's computeEnduserDocsIndex/
//     generateEnduserDocsIndex) — compute-without-writing is shared by the
//     write path and the `--check` drift mode below.
//   - bee's own standing exemption for `docs/decisions/index.md`: "never
//     hand-edited, complete by construction, byte-stable for the same
//     store" (DISCUSSION.md round 3/round 4) — this file REPLACES the old
//     hand-authored `docs/decisions/0000-index.md` for platform-scoped
//     decisions; item-scoped D-IDs (kind:'design', id:<item-id>) render
//     into CONTEXT.md instead (task 3), never here.

import fs from 'node:fs';
import path from 'node:path';
import { listWork, StoreError } from '../state/store.mjs';

export function indexPathFor(repoRoot) {
  return path.join(repoRoot, 'docs', 'decisions', 'index.md');
}

function escapeCell(text) {
  return String(text ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/**
 * Pure: render docs/decisions/index.md's markdown from state.decisions'
 * scope-carrying records. `kind: 'engine'` bookkeeping is excluded (never
 * platform-scoped, tsk-1ud D7); any record with no `scope` field (item-
 * level D-IDs, D3) is excluded too — this index is ONLY the platform/
 * repo-wide surface D4 names. Sorted by scope, then chronologically, so a
 * repeat call over an unchanged log produces byte-identical output
 * (the `--check` drift mode below depends on this determinism).
 *
 * `type: explanation` frontmatter (tsk-1lv-4): `docs/decisions/` is a
 * QUADRANT_DIR_ALIASES entry for the "explanation" Diataxis quadrant
 * (`enduser-index.mjs`) — every file the retired ADR corpus held carried
 * this same `type`, and `docs-index`/its own consistency test expect every
 * `.md` file under this dir to keep declaring it, generated index included.
 */
export function buildDecisionIndexMarkdown(decisions) {
  const scoped = (decisions ?? []).filter(
    (d) => d.kind !== 'engine' && typeof d.scope === 'string' && d.scope.trim(),
  );
  scoped.sort((a, b) => {
    if (a.scope !== b.scope) return a.scope < b.scope ? -1 : 1;
    return a.ts < b.ts ? -1 : a.ts > b.ts ? 1 : 0;
  });

  const lines = [
    '---',
    'type: explanation',
    'title: Decisions index',
    'generated: true',
    '---',
    '',
    '# Decisions index',
    '',
    '<!-- generated by `fgos decision-index` from state.decisions -- never hand-edit; a manual edit is overwritten on the next regenerate. -->',
    '',
  ];
  if (scoped.length === 0) {
    lines.push('_No platform/repo-wide decisions recorded yet._', '');
  } else {
    lines.push('| Scope | Decision | Rationale | Recorded |', '|---|---|---|---|');
    for (const d of scoped) {
      lines.push(`| ${escapeCell(d.scope)} | ${escapeCell(d.text)} | ${escapeCell(d.rationale)} | ${escapeCell(d.ts)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Compute the current decisions index in memory, without writing anything
 * — the read-only half shared by `fgos decision-index`'s write path and
 * its own `--check` drift mode (mirrors enduser-index-generate.mjs's
 * computeEnduserDocsIndex).
 */
export function computeDecisionIndex(repoRoot, fgosDir) {
  const indexPath = indexPathFor(repoRoot);
  let previousContent;
  try {
    previousContent = fs.readFileSync(indexPath, 'utf8');
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }
  const view = listWork(fgosDir);
  const nextContent = buildDecisionIndexMarkdown(view.decisions);
  return { indexPath, nextContent, previousContent, changed: previousContent !== nextContent };
}

/**
 * Regenerate and, if content actually changed, overwrite
 * docs/decisions/index.md. Idempotent: a second call with nothing new in
 * state.decisions reports `changed: false` and never touches the file.
 *
 * tsk-1lv review-fix F12: refuses instead of writing when the on-disk
 * file already has real rows and the freshly-computed content would have
 * none -- `merge.mjs`'s own comment on the removed collision-resolve
 * mechanism argued the `fgos-write-rejected` wall makes a hostile
 * regenerated index impossible to merge, but that wall only rejects
 * staged changes under `.fgos/`; this file is an ordinary tracked doc.
 * A `fgw/<id>` worktree never carries `.fgos/` (ADR0020), so running this
 * verb there with no real store to read from computes the "no decisions
 * yet" placeholder -- committing and merging THAT is a real, unguarded
 * way to silently blank every platform decision's projection, same shape
 * as F6's context-render fix. This guard closes that gap directly rather
 * than relying on a wall that was never built to cover it.
 */
export function generateDecisionIndex(repoRoot, fgosDir) {
  const { indexPath, nextContent, previousContent, changed } = computeDecisionIndex(repoRoot, fgosDir);
  const previousHasRows = typeof previousContent === 'string' && /^\|.+\|.*\|\s*$/m.test(previousContent);
  const nextHasRows = /^\|.+\|.*\|\s*$/m.test(nextContent);
  if (changed && previousHasRows && !nextHasRows) {
    throw new StoreError(
      'validation',
      `generateDecisionIndex: refusing to overwrite ${indexPath} -- it already has real rows and the freshly-computed content has none (a store with no decisions read, e.g. a worktree missing .fgos/ per ADR0020, or a genuine wipe -- either way this needs a person's look, not a silent overwrite).`,
    );
  }
  if (changed) {
    fs.mkdirSync(path.dirname(indexPath), { recursive: true });
    fs.writeFileSync(indexPath, nextContent, 'utf8');
  }
  return { path: path.relative(repoRoot, indexPath).split(path.sep).join('/'), changed, content: nextContent };
}
