// instruction-projections.test.mjs — P5 host-visible instruction projections.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  computeInstructionProjection,
  inspectInstructionProjection,
  materializeInstructionProjection,
  renderPortableAgentsProjection,
  MANAGED_BLOCK_START,
  MANAGED_BLOCK_END,
  PROJECTION_LEDGER_RELATIVE_PATH,
} from '../../src/setup/instruction-projections.mjs';
import { composeInstructionSet } from '../../src/setup/instruction-composition.mjs';
import { compileInstructionUnit } from '../../src/setup/instruction-registry.mjs';
import { DOCTOR_CHECKS, FIX_REGISTRATIONS } from '../../src/setup/checks.mjs';

function mkTempDir(prefix) {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function writeInstructionFile(root, name, frontmatter, body = '# Body\nInstruction text') {
  const dir = path.join(root, 'core', 'instructions');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, name), `---\n${frontmatter}\n---\n\n${body}\n`, 'utf8');
}

function compiledUnit(root, meta, body = '# Rule\nDo the thing.') {
  return compileInstructionUnit(meta, body, '', {
    projectRoot: root,
    fullPath: path.join(root, 'core', 'instructions', `${meta.id}.md`),
    sourcePath: `core/instructions/${meta.id}.md`,
    rootType: 'platform',
    rootOwner: 'core',
    knownOwners: new Set(['core']),
  });
}

function projectionCheck() {
  return DOCTOR_CHECKS.find((entry) => entry.id === 'instruction-projections-stale');
}

function projectionFix() {
  return FIX_REGISTRATIONS.find((entry) => entry.id === 'instruction-projections-stale');
}

function git(args, cwd) {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  }).trim();
}

test('renderPortableAgentsProjection renders a deterministic managed AGENTS.md block from the effective set', () => {
  const root = mkTempDir('fgos-instruction-projection-golden-');
  const set = composeInstructionSet([
    compiledUnit(root, {
      id: 'test-law',
      kind: 'law',
      title: 'Test Law',
      description: 'A deterministic law',
    }, '# Test Law\nAlways render through the effective set.'),
  ]);

  assert.equal(renderPortableAgentsProjection(set), [
    MANAGED_BLOCK_START,
    '<!-- generated by fgos instruction projection; edit canonical instruction sources, not this block -->',
    '<!-- effective-set: .fgos/instructions/effective/repo.json; key=repo; host=* -->',
    '',
    '## fgOS Effective Instructions',
    '',
    '### law',
    '',
    '#### Test Law',
    '',
    '- id: `test-law`',
    '- source: `core/instructions/test-law.md`',
    '',
    '# Test Law',
    'Always render through the effective set.',
    '',
    MANAGED_BLOCK_END,
    '',
  ].join('\n'));
});

test('materializeInstructionProjection writes effective JSON, managed AGENTS.md block, and projection ledger', () => {
  const root = mkTempDir('fgos-instruction-projection-materialize-');
  fs.writeFileSync(path.join(root, 'AGENTS.md'), '# Local Notes\n\nKeep this prose.\n', 'utf8');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );

  const result = materializeInstructionProjection(root);
  assert.equal(result.changed, true);

  const agents = fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8');
  assert.ok(agents.startsWith('# Local Notes\n\nKeep this prose.\n\n'));
  assert.match(agents, /<!-- fgos:instruction-projection:start -->/);
  assert.match(agents, /# Projection Law\nRender me\./);

  const effective = JSON.parse(fs.readFileSync(path.join(root, '.fgos/instructions/effective/repo.json'), 'utf8'));
  assert.deepEqual(effective.rules.map((rule) => rule.id), ['projection-law']);

  const ledger = JSON.parse(fs.readFileSync(path.join(root, PROJECTION_LEDGER_RELATIVE_PATH), 'utf8'));
  assert.equal(ledger.schemaVersion, 1);
  assert.equal(ledger.projections.length, 1);
  assert.equal(ledger.projections[0].destinationPath, 'AGENTS.md');
  assert.equal(ledger.projections[0].ownership, 'managed-block');
});

test('materializeInstructionProjection preserves unmanaged AGENTS.md prefix bytes', () => {
  const root = mkTempDir('fgos-instruction-projection-preserve-prefix-');
  const unmanagedPrefix = '# Personal notes  \n\n\n';
  fs.writeFileSync(path.join(root, 'AGENTS.md'), unmanagedPrefix, 'utf8');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );

  materializeInstructionProjection(root);

  const agents = fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8');
  assert.equal(agents.slice(0, unmanagedPrefix.length), unmanagedPrefix);
  assert.match(agents.slice(unmanagedPrefix.length), /<!-- fgos:instruction-projection:start -->/);
});

test('inspectInstructionProjection detects stale generated projections and fix repairs only the managed block', () => {
  const root = mkTempDir('fgos-instruction-projection-stale-');
  fs.writeFileSync(path.join(root, 'AGENTS.md'), '# Local Notes\n\nKeep this prose.\n', 'utf8');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );
  materializeInstructionProjection(root);
  assert.equal(inspectInstructionProjection(root).passed, true);

  const agentsPath = path.join(root, 'AGENTS.md');
  const stale = fs.readFileSync(agentsPath, 'utf8').replace('Render me.', 'Stale generated copy.');
  fs.writeFileSync(agentsPath, stale, 'utf8');

  const inspected = inspectInstructionProjection(root);
  assert.equal(inspected.passed, false);
  assert.ok(inspected.problems.some((problem) => problem.includes('managed instruction block stale')));

  const fixed = materializeInstructionProjection(root);
  assert.equal(fixed.changed, true);
  const repaired = fs.readFileSync(agentsPath, 'utf8');
  assert.ok(repaired.startsWith('# Local Notes\n\nKeep this prose.\n\n'));
  assert.match(repaired, /Render me\./);
});

test('doctor check is read-only, skips unmaterialized projections, and fix repairs stale instruction projections', () => {
  const root = mkTempDir('fgos-instruction-projection-doctor-');
  fs.writeFileSync(path.join(root, 'AGENTS.md'), '# Human content\n', 'utf8');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );

  const before = fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8');
  const check = projectionCheck();
  const fix = projectionFix();
  assert.ok(check, 'instruction-projections-stale check must be registered');
  assert.ok(fix, 'instruction-projections-stale fix must be registered');

  const firstCheck = check.check(root);
  assert.equal(firstCheck.passed, true);
  assert.match(firstCheck.message, /not materialized/);
  assert.equal(fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8'), before, 'doctor check must be read-only');

  const fixed = fix.fix(root);
  assert.equal(fixed.changed, true);
  assert.equal(check.check(root).passed, true);
  assert.ok(fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8').startsWith('# Human content\n\n'));

  const agentsPath = path.join(root, 'AGENTS.md');
  const stale = fs.readFileSync(agentsPath, 'utf8').replace('Render me.', 'Stale generated copy.');
  fs.writeFileSync(agentsPath, stale, 'utf8');
  const staleCheck = check.check(root);
  assert.equal(staleCheck.passed, false);
  assert.match(staleCheck.message, /managed instruction block stale/);
  assert.equal(fix.fix(root).changed, true);
  assert.equal(check.check(root).passed, true);
});

test('doctor check accepts a tracked managed AGENTS projection before workspace ledger materialization', () => {
  const root = mkTempDir('fgos-instruction-projection-tracked-agents-');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );
  materializeInstructionProjection(root);
  fs.rmSync(path.join(root, '.fgos'), { recursive: true, force: true });

  const check = projectionCheck();
  assert.ok(check, 'instruction-projections-stale check must be registered');
  assert.equal(check.check(root).passed, true);

  const agentsPath = path.join(root, 'AGENTS.md');
  fs.writeFileSync(
    agentsPath,
    fs.readFileSync(agentsPath, 'utf8').replace('Render me.', 'Stale generated copy.'),
    'utf8',
  );
  const stale = check.check(root);
  assert.equal(stale.passed, false);
  assert.match(stale.message, /managed instruction block stale/);
});

test('doctor check ignores unrelated projection ledger entries', () => {
  const root = mkTempDir('fgos-instruction-projection-unrelated-ledger-');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );
  const ledgerPath = path.join(root, PROJECTION_LEDGER_RELATIVE_PATH);
  fs.mkdirSync(path.dirname(ledgerPath), { recursive: true });
  fs.writeFileSync(ledgerPath, `${JSON.stringify({
    schemaVersion: 1,
    projections: [
      {
        id: 'skill:example',
        kind: 'skill-projection',
        destinationPath: '.agents/skills/example/SKILL.md',
      },
    ],
  }, null, 2)}\n`, 'utf8');

  const check = projectionCheck();
  assert.ok(check, 'instruction-projections-stale check must be registered');
  assert.equal(check.check(root).passed, true);
});

test('doctor fix resolves a linked worktree to the main checkout projection root', () => {
  const tmp = mkTempDir('fgos-instruction-projection-linked-');
  const main = path.join(tmp, 'main');
  const linked = path.join(tmp, 'linked');
  fs.mkdirSync(main, { recursive: true });
  git(['init'], main);
  git(['config', 'user.email', 'fgos@example.invalid'], main);
  git(['config', 'user.name', 'fgOS Test'], main);
  writeInstructionFile(
    main,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );
  git(['add', '.'], main);
  git(['commit', '-m', 'seed instructions'], main);
  git(['worktree', 'add', linked], main);

  const fix = projectionFix();
  const check = projectionCheck();
  assert.ok(fix, 'instruction-projections-stale fix must be registered');
  assert.ok(check, 'instruction-projections-stale check must be registered');

  const fixed = fix.fix(linked);
  assert.equal(fixed.changed, true);
  assert.equal(fs.existsSync(path.join(main, 'AGENTS.md')), true);
  assert.equal(fs.existsSync(path.join(main, '.fgos/instructions/effective/repo.json')), true);
  assert.equal(fs.existsSync(path.join(main, PROJECTION_LEDGER_RELATIVE_PATH)), true);
  assert.equal(fs.existsSync(path.join(linked, 'AGENTS.md')), false);
  assert.equal(fs.existsSync(path.join(linked, '.fgos/instructions/effective/repo.json')), false);
  assert.equal(check.check(linked).passed, true);
});

test('materializeInstructionProjection refuses malformed managed markers instead of overwriting user content', () => {
  const root = mkTempDir('fgos-instruction-projection-malformed-');
  fs.writeFileSync(path.join(root, 'AGENTS.md'), `# Human content\n\n${MANAGED_BLOCK_START}\nmissing end\n`, 'utf8');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );

  assert.throws(
    () => materializeInstructionProjection(root),
    /managed block markers are malformed/,
  );
  assert.match(fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8'), /missing end/);
  assert.equal(MANAGED_BLOCK_END, '<!-- fgos:instruction-projection:end -->');
});

test('instruction projection inspection rejects duplicate managed marker pairs', () => {
  const root = mkTempDir('fgos-instruction-projection-duplicate-markers-');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );
  materializeInstructionProjection(root);

  const agentsPath = path.join(root, 'AGENTS.md');
  fs.appendFileSync(
    agentsPath,
    `\n${MANAGED_BLOCK_START}\nsecond generated block\n${MANAGED_BLOCK_END}\n`,
    'utf8',
  );

  assert.throws(
    () => inspectInstructionProjection(root),
    /managed block markers are malformed/,
  );
  assert.throws(
    () => materializeInstructionProjection(root),
    /managed block markers are malformed/,
  );
});

test('instruction projection options reject unsupported host adapters and escaping destinations', () => {
  const root = mkTempDir('fgos-instruction-projection-options-');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );

  assert.throws(
    () => computeInstructionProjection(root, { host: 'claude' }),
    /Unsupported instruction projection host/,
  );
  assert.throws(
    () => materializeInstructionProjection(root, { destinationPath: '../AGENTS.md' }),
    /must stay inside the project root/,
  );
  assert.throws(
    () => materializeInstructionProjection(root, { destinationPath: path.join(root, 'AGENTS.md') }),
    /must be relative/,
  );
  assert.throws(
    () => materializeInstructionProjection(root, { destinationPath: '.' }),
    /must stay inside the project root/,
  );
  assert.throws(
    () => materializeInstructionProjection(root, { target: 'domain:/../../../../../escaped/pwned' }),
    /Effective instruction set key must be a portable file stem/,
  );
  assert.equal(fs.existsSync(path.join(path.dirname(root), 'escaped', 'pwned.json')), false);
  const packageJson = path.join(root, 'package.json');
  fs.writeFileSync(packageJson, '{"name":"fixture"}\n', 'utf8');
  assert.throws(
    () => materializeInstructionProjection(root, { target: 'domain:/../../../../package' }),
    /Effective instruction set key must be a portable file stem/,
  );
  assert.equal(fs.readFileSync(packageJson, 'utf8'), '{"name":"fixture"}\n');
});

test('instruction projection materialization rejects symlinked destinations', () => {
  const root = mkTempDir('fgos-instruction-projection-symlink-root-');
  const outside = mkTempDir('fgos-instruction-projection-symlink-outside-');
  const victim = path.join(outside, 'victim.md');
  fs.writeFileSync(victim, 'EXTERNAL HUMAN CONTENT\n', 'utf8');
  fs.symlinkSync(victim, path.join(root, 'AGENTS.md'));
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );

  assert.throws(
    () => materializeInstructionProjection(root),
    /must not cross a symlink/,
  );
  assert.equal(fs.readFileSync(victim, 'utf8'), 'EXTERNAL HUMAN CONTENT\n');
});

test('instruction projection materialization rejects dangling symlinked projection paths', () => {
  const root = mkTempDir('fgos-instruction-projection-dangling-link-root-');
  const outside = mkTempDir('fgos-instruction-projection-dangling-link-outside-');
  const agentsVictim = path.join(outside, 'planted-agents.md');
  fs.symlinkSync(agentsVictim, path.join(root, 'AGENTS.md'));
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    '# Projection Law\nRender me.',
  );

  assert.throws(
    () => materializeInstructionProjection(root),
    /must not cross a symlink/,
  );
  assert.equal(fs.existsSync(agentsVictim), false);

  fs.rmSync(path.join(root, 'AGENTS.md'));
  const ledgerPath = path.join(root, PROJECTION_LEDGER_RELATIVE_PATH);
  fs.mkdirSync(path.dirname(ledgerPath), { recursive: true });
  const ledgerVictim = path.join(outside, 'planted-ledger.json');
  fs.symlinkSync(ledgerVictim, ledgerPath);
  assert.throws(
    () => materializeInstructionProjection(root),
    /must not cross a symlink/,
  );
  assert.equal(fs.existsSync(ledgerVictim), false);
});

test('instruction projection materialization rejects managed marker literals in rendered content', () => {
  const root = mkTempDir('fgos-instruction-projection-marker-literal-');
  writeInstructionFile(
    root,
    'law.md',
    'id: projection-law\nkind: law\ntitle: Projection Law',
    `# Projection Law\nDo not edit ${MANAGED_BLOCK_END} by hand.`,
  );

  assert.throws(
    () => materializeInstructionProjection(root),
    /must not contain managed marker literals/,
  );
  assert.equal(fs.existsSync(path.join(root, 'AGENTS.md')), false);
});
