//! `apps/fgos` binary.
//!
//! Entry point for the fgOS platform host CLI.
//!
//! Scans arguments for host-global options (none recognized in R1), embeds
//! the checked `command-routes.json` routing descriptor, delegates legacy-cli
//! routes to `legacy_exec`, and routes native operations through the
//! `fgos-host-runtime` `InvocationService` kernel pipeline.

mod cli_presenter;
mod cli_projector;
mod legacy_exec;

use fgos_host_runtime::invocation_service::NoopEventSink;
use fgos_host_runtime::{
    build_snapshot, EchoProvider, InvocationService, ProviderDescriptor, CATALOG,
    ECHO_PROVIDER_DESCRIPTOR,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, OnceLock};

/// Embedded command-routes descriptor generated by Phase 01.
const COMMAND_ROUTES_JSON: &str =
    include_str!("../../../packages/host-runtime/contracts/command-routes.json");

/// Routing descriptor for one command selector.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandRouteDescriptor {
    pub selector: String,
    pub route_kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legacy_payload: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_id: Option<String>,
    pub owner_path: String,
    pub compatibility_tests: Vec<String>,
}

static ROUTES: OnceLock<HashMap<String, CommandRouteDescriptor>> = OnceLock::new();

/// Returns the embedded command route table parsed lazily once.
pub fn command_routes() -> &'static HashMap<String, CommandRouteDescriptor> {
    ROUTES.get_or_init(|| {
        serde_json::from_str(COMMAND_ROUTES_JSON)
            .expect("embedded command-routes.json must be valid JSON")
    })
}

/// Static provider table for the Phase 07 composition root: only in-crate echo fixture.
static COMPOSITION_PROVIDERS: &[ProviderDescriptor] = &[ECHO_PROVIDER_DESCRIPTOR];

fn main() {
    // Check recursion guard immediately. Fails closed if already set.
    if let Err(err) = legacy_exec::check_recursion_guard() {
        eprintln!("fgos: error: {}", err);
        std::process::exit(1);
    }

    let args: Vec<std::ffi::OsString> = std::env::args_os().collect();
    let cli_args = if args.len() > 1 { &args[1..] } else { &[] };

    // R1: Scan for host-global options only. In R1, no host-global options are
    // recognized. The first positional token is always the selector.
    let mut selector: Option<&str> = None;
    for arg in cli_args {
        if let Some(s) = arg.to_str() {
            if !s.starts_with('-') {
                selector = Some(s);
                break;
            }
        }
    }

    let selector = match selector {
        Some(s) if !s.is_empty() => s,
        _ => {
            // R3: Unlisted or missing selector fails closed with EXIT_CODES.validation = 4.
            let fallback_verb = cli_args.first().and_then(|a| a.to_str()).unwrap_or("");
            eprintln!(
                "fgos: unknown verb \"{}\". Usage: fgos <command> [args...]",
                fallback_verb
            );
            std::process::exit(4);
        }
    };

    let routes = command_routes();
    let route = match routes.get(selector) {
        Some(r) => r,
        None => {
            // R3: Unknown/unlisted selector fails closed with exit code 4.
            eprintln!(
                "fgos: unknown verb \"{}\". Usage: fgos <command> [args...]",
                selector
            );
            std::process::exit(4);
        }
    };

    // Composition root: build snapshot and InvocationService.
    let snapshot = build_snapshot(CATALOG, COMPOSITION_PROVIDERS, "fgos-composition-root-v1");
    let service = InvocationService::new(snapshot);
    service.register_provider(Arc::new(EchoProvider::new()));
    let tracker = service.tracker();

    match route.route_kind.as_str() {
        "legacy-cli" => {
            // Delegate to legacy-cli lane.
            legacy_exec::execute_legacy_cli(selector, &tracker, cli_args);
        }
        "native" => {
            use std::io::IsTerminal;
            if !std::io::stdin().is_terminal() {
                use std::io::Read;
                let _ = std::io::copy(
                    &mut std::io::stdin().take(1024 * 1024),
                    &mut std::io::sink(),
                );
            }

            let op_id_str = route
                .operation_id
                .as_deref()
                .unwrap_or("distribution.build.show");

            let (invocation, request) = cli_projector::project_cli_invocation(op_id_str, cli_args)
                .unwrap_or_else(|err| {
                    eprintln!("fgos: error: {}", err);
                    std::process::exit(1);
                });

            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("failed to build current-thread tokio runtime");

            let (res, record) = rt.block_on(async {
                service
                    .invoke_with_record(invocation, request, &NoopEventSink)
                    .await
            });

            legacy_exec::emit_invocation_record(&record);

            match res {
                Ok(outcome) => {
                    let code = cli_presenter::present_outcome(&outcome);
                    std::process::exit(code);
                }
                Err(err) => {
                    let code = cli_presenter::present_error(&err);
                    std::process::exit(code);
                }
            }
        }
        other => {
            eprintln!(
                "fgos: error: unsupported route_kind '{}' for selector '{}'",
                other, selector
            );
            std::process::exit(1);
        }
    }
}
